use_frameworks!

platform :ios, '10.0'

target 'MNWSDK_Example' do
  pod 'MNWSDK', :path => '../'

  target 'MNWSDK_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
