platform :ios, '12.0'
target 'YandexTest' do
  use_frameworks!
     pod 'YandexLoginSDK','3.0.2'
     pod 'AppsFlyerFramework','6.17.0'
     pod 'FBSDKLoginKit', '17.4.0'
#   pod 'YandexLoginSDK'
     pod 'MNWSDK', '~> 0.0.2'

end
